name: Build and Publish Angular Library

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # --------------------------------
      # Checkout
      # --------------------------------
      - uses: actions/checkout@v4

      # --------------------------------
      # Setup Node (default for npmjs)
      # --------------------------------
      - name: Setup Node for npmjs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Library
        run: npx ng build common-utilities

      - name: Set Auto Version
        run: |
          cd dist/common-utilities
          npm version 1.0.0-ci.${{ github.run_number }} --no-git-tag-version

      # ========================================
      # Publish to npmjs
      # ========================================
      - name: Publish to npmjs
        run: |
          cd dist/common-utilities
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # ========================================
      # Setup Node AGAIN for GitHub Packages
      # ========================================
      - name: Setup Node for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@SURERAKESHKUMAR'

      # ========================================
      # Publish to GitHub Packages
      # ========================================
      - name: Publish to GitHub Packages
        run: |
          cd dist/common-utilities
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
