name: Build and Publish Angular Library (NPM + GitHub)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # ----------------------------------------
      # Checkout repository
      # ----------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------
      # Setup Node
      # ----------------------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ----------------------------------------
      # Install dependencies (workspace root)
      # ----------------------------------------
      - name: Install dependencies
        run: npm ci

      # ----------------------------------------
      # Build Angular Library
      # ----------------------------------------
      - name: Build library
        run: npx ng build common-utilities

      # ----------------------------------------
      # Set Auto CI Version
      # ----------------------------------------
      - name: Set Auto Version
        run: |
          cd dist/common-utilities
          npm version 1.0.0-ci.${{ github.run_number }} --no-git-tag-version

      # ========================================
      # Publish to np
