name: Build and Publish Angular Library (NPM + GitHub)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # ----------------------------------------
      # Checkout Repository
      # ----------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------
      # Setup Node
      # ----------------------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ----------------------------------------
      # Install Dependencies (Workspace Root)
      # ----------------------------------------
      - name: Install Dependencies
        run: npm ci

      # ----------------------------------------
      # Build Angular Library
      # ----------------------------------------
      - name: Build Library
        run: npx ng build common-utilities

      # ----------------------------------------
      # Set Auto CI Version
      # ----------------------------------------
      - name: Set CI Version
        run: |
          cd dist/common-utilities
          npm version 1.0.0-ci.${{ github.run_number }} --no-git-tag-version

      # ========================================
      # Publish to npmjs
      # ========================================
      - name: Publish to npmjs
        run: |
          cd dist/common-utilities
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # ========================================
      # Publish to GitHub Packages (PAT METHOD)
      - name: Publish to GitHub Packages
        run: |
          cd dist/common-utilities
     
          echo "//npm.pkg.github.com/:_authToken=${GH_PAT}" > ~/.npmrc
          echo "@SURERAKESHKUMAR:registry=https://npm.pkg.github.com" >> ~/.npmrc

          npm publish --registry=https://npm.pkg.github.com
        env:
        GH_PAT: ${{ secrets.GH_PAT }}
